(function exposeNexoraPosData(root){
  'use strict';

  const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
  const mkSched=(offDays,from,to)=>DAYS.map(day=>({d:day,on:!offDays.includes(day),from,to}));
  const categoryList=['Pedicure','Manicure','Acrylic','Dipping'];
  const services=[
    {name:'Deluxe Pedicure',price:55,dur:50,cats:['Pedicure']},
    {name:'Classic Pedicure',price:35,dur:35,cats:['Pedicure']},
    {name:'Polish change',price:8,dur:15,cats:['Pedicure','Manicure']},
    {name:'Gel Manicure',price:40,dur:40,cats:['Manicure']},
    {name:'Classic Manicure',price:25,dur:25,cats:['Manicure']},
    {name:'Full Set',price:70,dur:60,cats:['Acrylic']},
    {name:'Fill',price:45,dur:45,cats:['Acrylic','Dipping']},
    {name:'Dip Powder',price:50,dur:45,cats:['Dipping']}
  ];
  const catalog=Object.fromEntries(categoryList.map(category=>[
    category,
    services.filter(service=>service.cats.includes(category))
  ]));
  const allServiceNames=()=>[...new Set(services.map(service=>service.name))];
  const categoryServiceNames=category=>catalog[category].map(service=>service.name);

  const source={
    locales:['en-US','vi-VN'],
    i18n:{
      'locale.english':{'en-US':'English (US)','vi-VN':'Tiếng Anh (Mỹ)'},
      'locale.vietnamese':{'en-US':'Vietnamese','vi-VN':'Tiếng Việt'},
      'locale.changed.en':{'en-US':'App language changed to English (US).','vi-VN':'Đã chuyển ngôn ngữ sang Tiếng Anh (Mỹ).'},
      'locale.changed.vi':{'en-US':'App language changed to Vietnamese.','vi-VN':'Đã chuyển ngôn ngữ sang Tiếng Việt.'},
      'app.description':{'en-US':'Manage orders, service tickets, bookings, and payments in one workspace.','vi-VN':'Quản lý đơn, phiếu dịch vụ, đặt lịch và thanh toán trong một không gian làm việc.'},
      'app.search.current':{'en-US':'Search this screen','vi-VN':'Tìm trong màn hiện tại'},
      'app.search.unavailable':{'en-US':'Search is not available','vi-VN':'Màn này không cần tìm kiếm'},
      'role.owner':{'en-US':'Owner','vi-VN':'Chủ tiệm'},
      'role.fullAccess':{'en-US':'Full access','vi-VN':'Toàn quyền'},
      'role.ownerLabel':{'en-US':'Owner · Full access','vi-VN':'Chủ tiệm · Toàn quyền'},
      'nav.today':{'en-US':'Today','vi-VN':'Hôm nay'},
      'nav.orders':{'en-US':'Orders','vi-VN':'Đơn'},
      'nav.tickets':{'en-US':'Tickets','vi-VN':'Phiếu dịch vụ'},
      'nav.booking':{'en-US':'Booking','vi-VN':'Đặt lịch'},
      'nav.customers':{'en-US':'Customers','vi-VN':'Khách hàng'},
      'nav.staff':{'en-US':'Staff','vi-VN':'Nhân viên'},
      'nav.report':{'en-US':'Report','vi-VN':'Báo cáo'},
      'nav.setup':{'en-US':'Setup','vi-VN':'Thiết lập'},
      'action.newOrder':{'en-US':'New Order','vi-VN':'Tạo đơn'},
      'action.checkIn':{'en-US':'Check-in','vi-VN':'Khách đến'},
      'action.more':{'en-US':'More','vi-VN':'Tác vụ khác'},
      'action.newBooking':{'en-US':'New Booking','vi-VN':'Tạo lịch'},
      'action.staffStatus':{'en-US':'Staff Status','vi-VN':'Trạng thái thợ'},
      'action.dailyReport':{'en-US':'Daily Report','vi-VN':'Báo cáo ngày'},
      'action.viewDetails':{'en-US':'View Details','vi-VN':'Xem chi tiết'},
      'action.details':{'en-US':'Details','vi-VN':'Chi tiết'},
      'action.checkout':{'en-US':'Checkout','vi-VN':'Thanh toán'},
      'action.receipt':{'en-US':'View Receipt','vi-VN':'Xem biên nhận'},
      'action.voidOrder':{'en-US':'Void','vi-VN':'Hủy đơn'},
      'action.assignTech':{'en-US':'Assign Tech','vi-VN':'Gán thợ'},
      'action.start':{'en-US':'Start','vi-VN':'Bắt đầu'},
      'action.startService':{'en-US':'Start Service','vi-VN':'Start Service'},
      'action.done':{'en-US':'Done','vi-VN':'Hoàn tất'},
      'action.viewTicket':{'en-US':'View Ticket','vi-VN':'Xem phiếu'},
      'action.clearFilters':{'en-US':'Clear Filters','vi-VN':'Xóa bộ lọc'},
      'action.close':{'en-US':'Close','vi-VN':'Đóng'},
      'action.save':{'en-US':'Save','vi-VN':'Lưu'},
      'status.open':{'en-US':'New','vi-VN':'Mới'},
      'status.waiting':{'en-US':'Waiting','vi-VN':'Chờ bắt đầu'},
      'status.inservice':{'en-US':'In Service','vi-VN':'Đang phục vụ'},
      'status.done':{'en-US':'Done','vi-VN':'Hoàn tất'},
      'status.ready':{'en-US':'Ready to Pay','vi-VN':'Chờ thanh toán'},
      'status.closed':{'en-US':'Paid','vi-VN':'Đã thanh toán'},
      'status.void':{'en-US':'Void','vi-VN':'Đã void'},
      'status.pending':{'en-US':'Pending','vi-VN':'Chờ xác nhận'},
      'status.confirmed':{'en-US':'Confirmed','vi-VN':'Đã xác nhận'},
      'status.checkedin':{'en-US':'Checked In','vi-VN':'Khách đã đến'},
      'status.converted':{'en-US':'Order Created','vi-VN':'Đã tạo đơn'},
      'status.cancelled':{'en-US':'Canceled','vi-VN':'Đã hủy lịch'},
      'filter.needsAttention':{'en-US':'Needs Attention','vi-VN':'Cần xử lý'},
      'filter.unassigned':{'en-US':'Unassigned','vi-VN':'Chưa gán thợ'},
      'filter.allOrders':{'en-US':'All Orders','vi-VN':'Tất cả đơn'},
      'filter.allTickets':{'en-US':'All Tickets','vi-VN':'Tất cả phiếu'},
      'filter.all':{'en-US':'All','vi-VN':'Tất cả'},
      'date.today':{'en-US':'Today','vi-VN':'Hôm nay'},
      'date.tomorrow':{'en-US':'Tomorrow','vi-VN':'Ngày mai'},
      'date.last7':{'en-US':'Last 7 days','vi-VN':'7 ngày qua'},
      'date.next7':{'en-US':'Today + 7 days','vi-VN':'Hôm nay + 7 ngày'},
      'date.custom':{'en-US':'From - To','vi-VN':'Từ ngày - đến ngày'},
      'date.all':{'en-US':'All dates','vi-VN':'Tất cả'},
      'unit.minute.one':{'en-US':'{count} minute','vi-VN':'{count} phút'},
      'unit.minute.other':{'en-US':'{count} minutes','vi-VN':'{count} phút'},
      'count.order.one':{'en-US':'{count} order','vi-VN':'{count} đơn'},
      'count.order.other':{'en-US':'{count} orders','vi-VN':'{count} đơn'},
      'count.ticket.one':{'en-US':'{count} ticket','vi-VN':'{count} phiếu'},
      'count.ticket.other':{'en-US':'{count} tickets','vi-VN':'{count} phiếu'},
      'count.service.one':{'en-US':'{count} service','vi-VN':'{count} dịch vụ'},
      'count.service.other':{'en-US':'{count} services','vi-VN':'{count} dịch vụ'},
      'count.product.one':{'en-US':'{count} product','vi-VN':'{count} sản phẩm'},
      'count.product.other':{'en-US':'{count} products','vi-VN':'{count} sản phẩm'},
      'card.order':{'en-US':'Order {id}','vi-VN':'Đơn {id}'},
      'card.checkIn':{'en-US':'Check-in','vi-VN':'Giờ check-in'},
      'card.services':{'en-US':'Services','vi-VN':'Dịch vụ'},
      'card.moreServices':{'en-US':'+{count} more','vi-VN':'+{count} dịch vụ khác'},
      'card.noServices':{'en-US':'No services added','vi-VN':'Chưa có dịch vụ'},
      'card.time':{'en-US':'Time','vi-VN':'Thời gian'},
      'card.tracking':{'en-US':'Progress','vi-VN':'Theo dõi'},
      'card.scope':{'en-US':'Items','vi-VN':'Quy mô'},
      'card.total':{'en-US':'Total','vi-VN':'Tổng tiền'},
      'card.waited':{'en-US':'Waited {count} minutes','vi-VN':'Đã chờ {count} phút'},
      'card.completed':{'en-US':'Completed','vi-VN':'Đã hoàn tất'},
      'card.voided':{'en-US':'Voided','vi-VN':'Đã void'},
      'card.trackTickets':{'en-US':'Open details to track service tickets','vi-VN':'Theo dõi các phiếu dịch vụ trong đơn'},
      'card.unassignedServices':{'en-US':'{count} services need a technician','vi-VN':'{count} dịch vụ cần gán thợ'},
      'card.allServicesDone':{'en-US':'All services are complete','vi-VN':'Tất cả dịch vụ đã hoàn tất'},
      'card.paidWith':{'en-US':'Paid with {method}','vi-VN':'Đã thu qua {method}'},
      'card.voidReason':{'en-US':'Reason: {reason}','vi-VN':'Lý do: {reason}'},
      'empty.title':{'en-US':'No matching results','vi-VN':'Không có kết quả phù hợp'},
      'empty.orders':{'en-US':'Try another keyword or clear the current filters.','vi-VN':'Thử từ khóa khác hoặc xóa bộ lọc hiện tại.'},
      'empty.today':{'en-US':'Change the status, wait threshold, or search keyword.','vi-VN':'Thử đổi trạng thái, ngưỡng chờ hoặc từ khóa tìm kiếm.'},
      'search.today':{'en-US':'Name, phone, order ID…','vi-VN':'Tên, SĐT, mã đơn…'},
      'search.orders':{'en-US':'Order, customer, service…','vi-VN':'Mã đơn, khách, dịch vụ…'},
      'search.tickets':{'en-US':'Customer, ticket, service…','vi-VN':'Khách, mã phiếu, dịch vụ…'},
      'search.booking':{'en-US':'Customer, phone, booking…','vi-VN':'Khách, SĐT, mã lịch…'},
      'search.customers':{'en-US':'Customer name or phone…','vi-VN':'Tên hoặc SĐT khách…'},
      'common.noPhone':{'en-US':'No phone number','vi-VN':'Chưa có SĐT'},
      'common.savedMethod':{'en-US':'saved method','vi-VN':'phương thức đã lưu'},
      'common.noNote':{'en-US':'No note','vi-VN':'Không có ghi chú'},
      'orders.management':{'en-US':'Order Management','vi-VN':'Quản lý đơn'},
      'tickets.history':{'en-US':'Service Ticket History','vi-VN':'Lịch sử phiếu dịch vụ'},
      'action.newCustomer':{'en-US':'New Customer','vi-VN':'Tạo khách hàng'},
      'action.addTechnician':{'en-US':'Add Technician','vi-VN':'Thêm thợ'},
      'action.confirm':{'en-US':'Confirm','vi-VN':'Xác nhận'},
      'action.cancelBooking':{'en-US':'Cancel Booking','vi-VN':'Hủy lịch'},
      'action.createOrder':{'en-US':'Create Order','vi-VN':'Tạo đơn'},
      'action.viewProfile':{'en-US':'View Profile','vi-VN':'Xem hồ sơ'},
      'entity.ticket':{'en-US':'Ticket {id}','vi-VN':'Phiếu {id}'},
      'entity.order':{'en-US':'Order {id}','vi-VN':'Đơn {id}'},
      'entity.booking':{'en-US':'Booking {id}','vi-VN':'Lịch {id}'},
      'entity.customer':{'en-US':'Customer','vi-VN':'Khách hàng'},
      'entity.technician':{'en-US':'Technician','vi-VN':'Thợ'},
      'entity.services':{'en-US':'Services','vi-VN':'Dịch vụ'},
      'entity.note':{'en-US':'Note','vi-VN':'Ghi chú'},
      'entity.source':{'en-US':'Source','vi-VN':'Nguồn'},
      'entity.requestedTech':{'en-US':'Requested Tech','vi-VN':'Thợ hẹn'},
      'entity.schedule':{'en-US':'Date & Time','vi-VN':'Ngày giờ'},
      'entity.bookings':{'en-US':'Bookings','vi-VN':'Lịch hẹn'},
      'entity.orders':{'en-US':'Orders','vi-VN':'Đơn'},
      'entity.recentActivity':{'en-US':'Recent Activity','vi-VN':'Hoạt động gần nhất'},
      'entity.estimatedPrice':{'en-US':'Estimated Price','vi-VN':'Giá tham khảo'},
      'entity.bookingSource':{'en-US':'Booking Source','vi-VN':'Nguồn booking'},
      'entity.createdAt':{'en-US':'Created At','vi-VN':'Tạo lúc'},
      'entity.cancelReason':{'en-US':'Cancellation Reason','vi-VN':'Lý do hủy'},
      'entity.linkedOrder':{'en-US':'Linked Order','vi-VN':'Order liên kết'},
      'entity.linkedTicket':{'en-US':'Linked Ticket','vi-VN':'Ticket liên kết'},
      'common.any':{'en-US':'Any','vi-VN':'Bất kỳ'},
      'common.todayAt':{'en-US':'Today · {time}','vi-VN':'Hôm nay · {time}'},
      'ticket.closedTransaction':{'en-US':'Transaction closed','vi-VN':'Giao dịch đã đóng'},
      'ticket.servicesForOrder':{'en-US':'Services for order {id}','vi-VN':'Dịch vụ thuộc đơn {id}'},
      'ticket.notCreated':{'en-US':'No service ticket created','vi-VN':'Chưa tạo phiếu dịch vụ'},
      'ticket.needsAction':{'en-US':'Needs action','vi-VN':'Cần xử lý'},
      'ticket.belongsToOrder':{'en-US':'Ticket for order {id}','vi-VN':'Phiếu thuộc đơn {id}'},
      'ticket.doneAwaitingCheckout':{'en-US':'Completed · awaiting order checkout','vi-VN':'Đã hoàn tất · chờ đơn thanh toán'},
      'ticket.paidWithOrder':{'en-US':'Paid with order','vi-VN':'Đã thanh toán theo đơn'},
      'ticket.voidNoRevenue':{'en-US':'Voided · {reason}','vi-VN':'Đã void · {reason}'},
      'ticket.noRevenue':{'en-US':'excluded from revenue','vi-VN':'không tính doanh thu'},
      'booking.awaitingAction':{'en-US':'Appointment is awaiting action','vi-VN':'Lịch hẹn đang chờ xử lý'},
      'booking.readyToday':{'en-US':'Ready for today\'s arrival','vi-VN':'Sẵn sàng đón khách hôm nay'},
      'booking.notToday':{'en-US':'Appointment date has not arrived','vi-VN':'Chưa đến ngày hẹn'},
      'booking.arrivedReady':{'en-US':'Customer arrived · ready to create order','vi-VN':'Khách đã đến · sẵn sàng tạo đơn'},
      'booking.converted':{'en-US':'Created {type} {id}','vi-VN':'Đã tạo {type} {id}'},
      'booking.type.ticket':{'en-US':'ticket','vi-VN':'phiếu'},
      'booking.type.order':{'en-US':'order','vi-VN':'đơn'},
      'customer.noHistory':{'en-US':'No history yet','vi-VN':'Chưa có lịch sử'},
      'count.booking.one':{'en-US':'{count} booking','vi-VN':'{count} lịch'},
      'count.booking.other':{'en-US':'{count} bookings','vi-VN':'{count} lịch'},
      'stats.customerProfiles':{'en-US':'Customer Profiles','vi-VN':'Hồ sơ khách'},
      'stats.withBookings':{'en-US':'With Bookings','vi-VN':'Có lịch hẹn'},
      'stats.withOrders':{'en-US':'With Order History','vi-VN':'Có lịch sử đơn'},
      'stats.arrivedToday':{'en-US':'Arrived Today','vi-VN':'Đã đến hôm nay'},
      'stats.openOrders':{'en-US':'Open Orders','vi-VN':'Đơn đang mở'},
      'stats.tipsToday':{'en-US':'Tips Today','vi-VN':'Tips hôm nay'},
      'stats.bookingsToday':{'en-US':'Bookings Today','vi-VN':'Booking hôm nay'},
      'stats.onShift':{'en-US':'On Shift','vi-VN':'Đang trong ca'},
      'stats.turnsToday':{'en-US':'Turns Today','vi-VN':'Tổng turn hôm nay'},
      'stats.salonAverage':{'en-US':'Salon Average','vi-VN':'Trung bình tiệm'},
      'stats.totalTechnicians':{'en-US':'Total Technicians','vi-VN':'Tổng thợ'},
      'staff.technician':{'en-US':'Technician','vi-VN':'Nhân viên'},
      'staff.commission':{'en-US':'Commission {value}','vi-VN':'Hoa hồng {value}'},
      'staff.onShift':{'en-US':'On Shift','vi-VN':'Đang trong ca'},
      'staff.shiftEnded':{'en-US':'Shift Ended','vi-VN':'Đã kết thúc ca'},
      'staff.active':{'en-US':'Active','vi-VN':'Đang làm việc'},
      'staff.inactive':{'en-US':'Inactive','vi-VN':'Ngừng hợp tác'},
      'staff.workSchedule':{'en-US':'Work Schedule','vi-VN':'Lịch làm'},
      'staff.clockIn':{'en-US':'Clock-in','vi-VN':'Bắt đầu ca'},
      'staff.clockOut':{'en-US':'Clock-out','vi-VN':'Kết thúc ca'},
      'staff.turns':{'en-US':'Turns Today','vi-VN':'Lượt hôm nay'},
      'staff.employment':{'en-US':'Employment','vi-VN':'Hợp tác'},
      'count.technician.one':{'en-US':'{count} technician','vi-VN':'{count} thợ'},
      'count.technician.other':{'en-US':'{count} technicians','vi-VN':'{count} thợ'},
      'count.customer.one':{'en-US':'{count} customer','vi-VN':'{count} khách'},
      'count.customer.other':{'en-US':'{count} customers','vi-VN':'{count} khách'},
      'count.day.one':{'en-US':'{count} day','vi-VN':'{count} ngày'},
      'count.day.other':{'en-US':'{count} days','vi-VN':'{count} ngày'},
      'staff.noSchedule':{'en-US':'No schedule','vi-VN':'Chưa xếp lịch'},
      'staff.variesByDay':{'en-US':'varies by day','vi-VN':'theo ngày'},
      'empty.customers':{'en-US':'Try a name or phone number, or clear the search.','vi-VN':'Thử tên, số điện thoại hoặc xóa từ khóa tìm kiếm.'},
      'notification.needsAction':{'en-US':'Needs Action','vi-VN':'Cần xử lý'},
      'notification.priorityHint':{'en-US':'Prioritized by impact and wait time','vi-VN':'Ưu tiên theo ảnh hưởng và thời gian chờ'},
      'notification.urgent':{'en-US':'Urgent','vi-VN':'Khẩn cấp'},
      'notification.urgentHint':{'en-US':'Work currently blocking operations','vi-VN':'Công việc đang chặn vận hành'},
      'notification.payment':{'en-US':'Payment','vi-VN':'Thanh toán'},
      'notification.paymentHint':{'en-US':'Proof, Ready to Pay, and add-ons need review','vi-VN':'Proof, Ready to Pay và add-on cần duyệt'},
      'notification.waiting':{'en-US':'Customers Waiting','vi-VN':'Khách đang chờ'},
      'notification.waitingHint':{'en-US':'Kiosk customers awaiting Front Desk','vi-VN':'Khách kiosk chờ Front Desk tiếp nhận'},
      'notification.booking':{'en-US':'Booking','vi-VN':'Booking'},
      'notification.bookingHint':{'en-US':'New or recently canceled bookings','vi-VN':'Booking mới hoặc vừa hủy'},
      'notification.items':{'en-US':'{count} items','vi-VN':'{count} mục'},
      'notification.noUrgent':{'en-US':'No urgent work.','vi-VN':'Không có công việc khẩn cấp.'},
      'notification.noReady':{'en-US':'No orders are Ready to Pay.','vi-VN':'Không có order Ready to Pay.'},
      'notification.noBooking':{'en-US':'No bookings need attention.','vi-VN':'Không có Booking cần theo dõi.'},
      'notification.noContent':{'en-US':'Nothing needs attention.','vi-VN':'Không có nội dung cần xử lý.'},
      'notification.waitingSince':{'en-US':'waiting since {time}','vi-VN':'chờ từ {time}'},
      'notification.newBooking':{'en-US':'New Booking','vi-VN':'Booking mới'},
      'notification.canceledBooking':{'en-US':'Booking {id} canceled','vi-VN':'Booking {id} đã hủy'},
      'date.orderTodayHint':{'en-US':'Orders from the current day only','vi-VN':'Chỉ order trong ngày hiện tại'},
      'date.orderWeekHint':{'en-US':'Orders from the current operating week','vi-VN':'Order trong tuần đang vận hành'},
      'date.ticketTodayHint':{'en-US':'Tickets from the current day only','vi-VN':'Chỉ ticket trong ngày hiện tại'},
      'date.ticketWeekHint':{'en-US':'History from the current operating week','vi-VN':'Lịch sử tuần đang vận hành'},
      'date.bookingWeekHint':{'en-US':'Appointments in the next 7 days','vi-VN':'Lịch hẹn đang vận hành trong tuần'},
      'date.bookingTodayHint':{'en-US':'Bookings from the current day only','vi-VN':'Chỉ booking trong ngày hiện tại'},
      'date.bookingTomorrowHint':{'en-US':'Prepare tomorrow\'s appointments','vi-VN':'Chuẩn bị lịch hẹn ngày kế tiếp'},
      'date.customHint':{'en-US':'Choose a specific date range','vi-VN':'Chọn khoảng ngày cụ thể'},
      'date.allHint':{'en-US':'No date limit','vi-VN':'Không giới hạn khoảng ngày'},
      'date.allBookings':{'en-US':'All bookings','vi-VN':'Tất cả booking'},
      'action.apply':{'en-US':'Apply','vi-VN':'Áp dụng'},
      'action.fullScreen':{'en-US':'Full screen','vi-VN':'Toàn màn hình'},
      'action.collapseSidebar':{'en-US':'Collapse sidebar','vi-VN':'Thu gọn sidebar'},
      'action.signOut':{'en-US':'Sign out','vi-VN':'Đăng xuất'},
      'action.profile':{'en-US':'Profile','vi-VN':'Hồ sơ'},
      'app.notifications':{'en-US':'Notifications','vi-VN':'Thông báo'},
      'setup.appLanguage':{'en-US':'App language','vi-VN':'Ngôn ngữ ứng dụng'},
      'setup.languageNote':{'en-US':'Applies to the POS tablet for every signed-in role. Staff workspace language is selected separately.','vi-VN':'Áp dụng cho POS tablet với mọi role đăng nhập. Ngôn ngữ Staff workspace được chọn riêng.'}
    },
    staticI18n:[
      ['Today · Houston branch · POS close day','Hôm nay · Houston branch · POS close day'],
      ['Salon Configuration — Salon Information','Cấu Hình Tiệm — Thông Tin Tiệm'],
      ['System Data','Dữ liệu hệ thống'],
      ['Centralized data source','Nguồn dữ liệu tập trung'],
      ['for POS, Kiosk, Staff App, and Customer App. Changes are saved through the web app and shown consistently on authorized screens.','cho POS, Kiosk, Staff App và Customer App. Mọi thay đổi được lưu qua web app và hiển thị nhất quán trên các màn hình được phân quyền.'],
      ['The system provides a permission catalog; the Owner creates roles and selects permissions for each role.','Hệ thống cung cấp permission catalog; Owner tạo role và chọn quyền cho từng role.'],
      ['Each staff member has one role.','Mỗi staff chỉ có một role.'],
      ['Built-in Owner always has full access. Currently: Cashier cannot see Setup; Void and Close Day require Manager or above. Switch roles at sign-in to verify.','Built-in Owner được khóa full access. Đang áp dụng: Cashier ẩn tab Setup, Void/Close Day cần Manager trở lên — đổi role ở màn đăng nhập để kiểm chứng.'],
      ['Add Technician','Thêm Thợ'],
      ['Select Edit to configure the receiving account for each payment method. Front Desk sees this information at checkout. Zelle, Venmo, Apple Cash, and Cash App are grouped under Other.','Bấm Edit để cấu hình tài khoản nhận từng phương thức — hiển thị cho lễ tân khi checkout. Zelle / Venmo / Apple Cash / Cash App nằm trong nhóm "Other".'],
      ['Look up customers and manage appointments at the counter','Tra cứu khách và tiếp nhận lịch hẹn tại quầy'],
      ['Find Customer','Tìm khách'],
      ['Recent Customers','Khách gần đây'],
      ['0 profiles','0 hồ sơ'],
      ['Quick Actions','Thao tác nhanh'],
      ['Walk-in profile · current salon time · draft ticket','Hồ sơ khách vãng lai · giờ hiện tại của tiệm · bản nháp phiếu'],
      ['Continue as Walk-in','Tiếp tục với khách vãng lai'],
      ['Create New Customer','Tạo khách hàng mới'],
      ['Matching Appointments','Lịch hẹn phù hợp'],
      ["Today's confirmed appointments",'Lịch hẹn đã xác nhận hôm nay'],
      ['Keep the booked services and technician','Giữ nguyên dịch vụ và thợ đã hẹn'],
      ['Staff payroll, commission, and receiving-method information is hidden from customer order history.','Thông tin payroll/commission/receive method của staff không hiển thị trong customer order history.'],
      ['An Order is the customer bill; a Ticket is the service record assigned to a technician.','Order là hóa đơn khách, Ticket là phiếu dịch vụ của thợ'],
      ['· prioritize skill match and show only technicians on shift','· ưu tiên skill match, chỉ hiện thợ đang trong ca'],
      ['Select at least one service and one technician.','Cần chọn ít nhất một service và technician.'],
      ['Ticket price','Giá theo ticket'],
      ['Assigned Technician','Thợ phụ trách'],
      ['Can be changed before checkout','Có thể đổi trước khi checkout'],
      ['Open the customer QR or send the ticket link from POS.','Mở QR cho khách hoặc gửi link ticket từ POS.'],
      ['Amount Due','Cần thu'],
      ['Customer payment','Khách thanh toán'],
      ['Quick Cash — Amount Received','Quick cash — tiền nhận'],
      ['Exact Amount','Đủ tiền'],
      ['Manual Entry / Amount','Nhập tay / Amount'],
      ['Received','Received / Tiền nhận'],
      ['Change','Change / Tiền thối'],
      ['Record payment from the card terminal. If the terminal fails, choose another method or No-QR fallback.','Ghi nhận thanh toán qua máy thẻ / terminal. Nếu terminal lỗi, chọn phương thức khác hoặc No-QR fallback.'],
      ['Waiting for payment… customer scans with the VLinkPay app','Waiting for payment… khách quét bằng app VLinkPay'],
      ['Simulate Expired QR','Giả lập QR hết hạn'],
      ['Select Payment Method','Chọn phương thức'],
      ['The customer sends proof through SMS or an external app. POS creates a verification request for Front Desk to Approve or Reject before closing the order.','Khách gửi proof qua SMS/app ngoài. POS sẽ tạo yêu cầu verify để Front Desk Approve hoặc Reject trước khi đóng order.'],
      ['Customer QR / Fallback','QR khách / Fallback'],
      ['Enter enough Cash received to cover the bill.','Chọn số tiền Cash đã nhận đủ bill.'],
      ['Customer cannot scan QR','Khách không quét QR'],
      ['Step 1 — Review the Bill','Step 1 — Đọc bill cho khách'],
      ['Step 2 — Ask for Tip','Step 2 — Hỏi tip'],
      ['Step 3 — Payment Method','Step 3 — Phương thức thanh toán'],
      ['Cash Due','Cash due / Cần thu'],
      ['Amount Received','Amount received / Tiền nhận'],
      ['Verify the Order, total, payment method, and amount received before closing.','Kiểm tra đúng Order, total, payment method và tiền nhận trước khi đóng.'],
      ['Select a tip to continue.','Chọn tip để tiếp tục.'],
      ['Back to Checkout','Quay lại Checkout'],
      ["Detailed weekly and monthly payroll uses today's data as its source.",'Payroll tuần/tháng chi tiết dùng dữ liệu hôm nay làm nguồn tính toán.'],
      ['Salon Information','Thông Tin Tiệm'],
      ['Salon Name','Tên tiệm'],
      ['Salon Phone Number','Số điện thoại tiệm'],
      ['Shown on booking and receipts, and used for incoming customer calls.','Số khách gọi vào tiệm và hiển thị trên booking/receipt.'],
      ['Booking Notification Number','Số nhận thông báo booking'],
      ['Receives SMS for new bookings and messages; use the Owner or Manager number.','SMS báo khi có khách book/nhắn — số chủ hoặc quản lý.'],
      ['Address','Địa chỉ'],
      ['Weekly Hours — select Day off for closed days','Giờ làm việc trong tuần — tick "Day off" cho ngày nghỉ'],
      ['Save Configuration','Lưu Cấu Hình'],
      ['Owner creates roles and selects permissions from the permission catalog','Owner tạo role và chọn quyền từ permission catalog'],
      ['The system provides a fixed permission catalog. The Owner creates or edits roles and selects permissions for each role;','Hệ thống cung cấp danh mục quyền cố định (permission catalog). Owner tạo/chỉnh role và chọn quyền cho từng role;'],
      ['always has full access and is locked from editing or deletion. Each role needs a unique name and at least one permission.','luôn full access và được khóa — không thể sửa hoặc xóa. Mỗi role cần tên duy nhất và ít nhất một quyền.'],
      ['Add New Role','Thêm role mới'],
      ['Save Roles','Lưu role'],
      ['Account Configuration','Cấu hình tài khoản'],
      ['Receiving Account *','Tài khoản nhận *'],
      ['Account Holder Name','Tên chủ tài khoản'],
      ['Receiving Asset Type','Loại asset nhận'],
      ['Checkout Display Note','Ghi chú hiển thị khi checkout'],
      ['Front Desk sees this information at checkout to guide the customer to the correct receiving account.','Thông tin này hiển thị cho lễ tân ở bước checkout để hướng dẫn khách chuyển đúng tài khoản.'],
      ['Booking Details','Chi tiết booking'],
      ['History','Lịch sử'],
      ['Date','Ngày'],
      ['Time','Giờ'],
      ['Customer Name','Tên khách'],
      ['Phone Number','Số điện thoại'],
      ['Bookings created here use the','Booking tạo tại đây mang nguồn'],
      ['. Other sources arrive automatically:','. Các nguồn khác đổ về tự động:'],
      ['. New bookings start as','. Booking mới vào'],
      ['— Confirm from Notifications or Booking; then Check-in and Create Order & Tickets to build the customer bill and technician service tickets.','— Confirm từ Notifications hoặc bảng Booking; khách đến Check-in → Create Order & Tickets để tạo hóa đơn khách và phiếu dịch vụ theo thợ.'],
      ['Create Booking','Tạo Booking'],
      ['Select Technician from Nexora','Chọn thợ từ Nexora'],
      ['Enter New Technician Manually','Tự nhập thợ mới'],
      ['Technician Name','Tên thợ'],
      ['Role — Each staff member has one role','Role — Mỗi staff chỉ có một role'],
      ['Inactive pauses new assignments while preserving history.','Inactive = tạm ngưng nhận khách, giữ lịch sử.'],
      ['Contract Type','Loại hợp đồng'],
      ['Weekly Salary','Lương tuần'],
      ['Custom Agreement','Thỏa thuận'],
      ['A technician can provide multiple services or an entire category.','Một thợ có thể nhận nhiều service hoặc cả category.'],
      ['Enter a name and phone number, then select at least one service.','Nhập tên, số điện thoại và chọn ít nhất một service.'],
      ['Weekly Work Hours','Giờ làm việc trong tuần'],
      ['Select a day (Mon–Sun) to toggle work status; set start and end times for each day.','Bấm vào ngày (T2…CN) để bật/tắt ngày làm; mỗi ngày chỉnh giờ vào – giờ ra riêng.'],
      ['Create New Category','Tạo category mới'],
      ['Category Name *','Tên category *'],
      ['Enter a category name.','Nhập tên category.'],
      ['Create New Service','Tạo service mới'],
      ['Service Name *','Tên service *'],
      ['(select to change group)','(bấm để chuyển nhóm)'],
      ['Price ($) *','Giá ($) *'],
      ['Duration (minutes)','Thời lượng (phút)'],
      ['Enter the service name, price, and duration.','Nhập tên, giá và thời lượng service.'],
      ['1 · Select a Product to Edit','1 · Chọn product để sửa'],
      ['Create New Product','Tạo product mới'],
      ['2 · Product Information','2 · Thông tin product'],
      ['Product Name *','Tên product *'],
      ['(a product can belong to multiple categories)','(một product có thể thuộc nhiều category)'],
      ['Sale Price ($) *','Giá bán ($) *'],
      ['Preview — chip shown when adding to an order','Preview — chip khi thêm vào order'],
      ['Enter a name and price, then select a category.','Nhập tên, giá và chọn category.'],
      ['Enable or disable Cash','Bật hoặc tắt Cash'],
      ['Enable or disable VLinkPay','Bật hoặc tắt VLinkPay'],
      ['Enable or disable Zelle','Bật hoặc tắt Zelle'],
      ['Enable or disable Venmo','Bật hoặc tắt Venmo'],
      ['Enable or disable Apple Cash','Bật hoặc tắt Apple Cash'],
      ['Enable or disable Cash App','Bật hoặc tắt Cash App'],
      ['Enable or disable Card','Bật hoặc tắt Card'],
      ['Phone or customer name…','SĐT hoặc tên khách…'],
      ['Optional note… (e.g. warm water)','Optional note… (vd: khách thích nước ấm)'],
      ['Customer rating','Đánh giá khách hàng'],
      ['E.g. accept saved contacts only','Vd: chỉ nhận từ số đã lưu danh bạ'],
      ['Search technicians','Tìm thợ'],
      ['Enable or disable Active status','Bật hoặc tắt trạng thái Active'],
      ['Enable or disable Tips','Bật hoặc tắt Tips'],
      ['Search service / category…','Tìm service / category…'],
      ['Search product / category…','Tìm product / category…'],
      ['Enable or disable Product','Bật hoặc tắt Product'],
      ['Commission / Weekly Salary / Agreement','Commission / Lương tuần / Thỏa thuận'],
      ['Service rating','Đánh giá dịch vụ'],
      ['Role name *','Tên role *'],
      ['Description (optional)','Mô tả (tùy chọn)'],
      ['Delete role','Xóa role']
    ],
    tax:0.0825,
    sequences:{order:110,booking:105,proof:302,addon:402},
    promos:[['No promo','none',0],['NEW10','pct',0.10],['VIP15','pct',0.15],['$5 OFF','amt',5]],
    categoryList,
    services,
    catalog,
    productCategories:['Retail','Aftercare'],
    products:[
      {name:'Cuticle Oil',price:12,cats:['Retail','Aftercare'],active:true},
      {name:'Hand Cream',price:18,cats:['Retail'],active:true},
      {name:'Nail File Kit',price:8,cats:['Aftercare'],active:true},
      {name:'Gel Removal Wraps',price:10,cats:['Aftercare'],active:true}
    ],
    customers:[
      {name:'Amy Nguyen',phone:'832-***-5555',last:'Deluxe Pedicure · Jul 08',note:'Thích nước ấm',tags:['VIP','Nước ấm'],notes:{owner:'Được áp dụng VIP15 khi phục vụ chậm.',staff:'Thích nước ấm và ghế yên tĩnh.',customer:'Chào mừng Amy quay lại.'}},
      {name:'Lisa Tran',phone:'713-***-2201',last:'Gel Manicure · Jul 05',note:'Ưu tiên Jenny nếu có',tags:['Ưu tiên thợ nữ'],notes:{owner:'Ưu tiên Jenny khi lịch làm việc cho phép.',staff:'Khách ưu tiên thợ nữ.',customer:'Yêu cầu Jenny khi có lịch trống.'}},
      {name:'Mary Le',phone:'281-***-8930',last:'Pedicure · Jun 30',note:'Ưu tiên ghế số 3',tags:['Cần chăm sóc thêm'],notes:{owner:'Khách cần chăm sóc thêm, không phục vụ vội.',staff:'Ưu tiên ghế số 3. Kiểm tra độ thoải mái trước khi sơn.',customer:'Tiệm đã ghi nhận ghế bạn yêu thích.'}},
      {name:'Nancy Vo',phone:'832-***-1188',last:'Full Set · Jun 28',note:'',tags:[],notes:{owner:'',staff:'',customer:''}},
      {name:'Olivia Pham',phone:'713-***-3408',last:'Classic Pedicure · Jul 01',note:'',tags:[],notes:{owner:'',staff:'',customer:''}},
      {name:'Sophia Bui',phone:'832-***-6714',last:'Full Set · Jun 29',note:'Thích form almond',tags:['Almond shape'],notes:{owner:'',staff:'Thích form almond, kiểm tra độ dài trước khi sơn.',customer:'Tiệm đã lưu form móng bạn yêu thích.'}},
      {name:'Linda Ho',phone:'281-***-4476',last:'Classic Pedicure · Jul 03',note:'',tags:[],notes:{owner:'',staff:'',customer:''}},
      {name:'Chloe Dao',phone:'346-***-8821',last:'Gel Manicure · Jul 07',note:'Ưu tiên màu trung tính',tags:['Neutral colors'],notes:{owner:'',staff:'Ưu tiên bảng màu trung tính.',customer:'Tiệm đã ghi nhận màu bạn yêu thích.'}},
      {name:'Jessica Truong',phone:'713-***-9055',last:'Classic Manicure · Jun 25',note:'',tags:[],notes:{owner:'',staff:'',customer:''}},
      {name:'Emily Nguyen',phone:'832-***-1260',last:'Dip Powder · Jul 02',note:'Dị ứng latex',tags:['Latex allergy'],notes:{owner:'Đảm bảo khu vực phục vụ không dùng latex.',staff:'Dị ứng latex — dùng găng nitrile.',customer:'Tiệm đã ghi nhận lưu ý dị ứng.'}}
    ],
    days:DAYS,
    staff:[
      {name:'Jenny Tran',short:'Jenny',phone:'+1 (832) 555-7712',email:'jenny@bitcoinnailbar.com',role:'Technician',services:[...categoryServiceNames('Pedicure'),'Gel Manicure'],sms:true,schedule:mkSched(['Sun'],'09:00','18:00'),contract:'Commission',comm:'60%',tips:true,cin:'8:58 AM',cout:null,turn:4,clocked:true,link:'Active',nexoraId:'NX-88921',vlinkId:'VL-55291',payout:'VLinkPay',receiveMethod:'VLinkPay',payroll:'Commission 60% · weekly review'},
      {name:'Tina Vo',short:'Tina',phone:'+1 (713) 555-0148',email:'tina@bitcoinnailbar.com',role:'Technician',services:[...categoryServiceNames('Acrylic'),...categoryServiceNames('Dipping')],sms:true,schedule:mkSched(['Sun'],'09:00','18:00'),contract:'Commission',comm:'60%',tips:true,cin:'9:12 AM',cout:null,turn:3,clocked:true,link:'Active',nexoraId:'NX-88104',vlinkId:'VL-55322',payout:'VLinkPay',receiveMethod:'VLinkPay',payroll:'Commission 60% · weekly review'},
      {name:'Kevin Nguyen',short:'Kevin',phone:'+1 (281) 555-9034',email:'kevin@bitcoinnailbar.com',role:'Technician',services:categoryServiceNames('Pedicure'),sms:true,schedule:mkSched(['Mon'],'10:00','19:00'),contract:'Commission',comm:'55%',tips:true,cin:'9:58 AM',cout:null,turn:2,clocked:true,link:'Active',nexoraId:'NX-89230',vlinkId:'VL-55890',payout:'VLinkPay',receiveMethod:'Zelle',payroll:'Commission 55% · weekly review'},
      {name:'Hana Le',short:'Hana',phone:'+1 (832) 555-4471',email:'hana@bitcoinnailbar.com',role:'Technician',services:allServiceNames(),sms:true,schedule:mkSched(['Mon','Tue'],'12:00','20:00'),contract:'Thỏa thuận',comm:'—',tips:false,cin:null,cout:null,turn:0,clocked:false,link:'Active',nexoraId:'NX-90112',vlinkId:'VL-56001',payout:'VLinkPay',receiveMethod:'Check',payroll:'Manual agreement · Owner review'}
    ],
    permissionCatalog:[
      {key:'booking',label:'Booking management'},
      {key:'customer',label:'Customer management'},
      {key:'orderticket',label:'Order & Ticket management'},
      {key:'checkout',label:'Checkout'},
      {key:'void',label:'Void'},
      {key:'staff',label:'Staff management'},
      {key:'report',label:'Daily Report'},
      {key:'payment',label:'Payment setup'}
    ],
    salonRoles:[],
    orders:[],
    tickets:[],
    bookings:[
      {id:'B-101',customer:'Andy Levi',phone:'+1 (832) 555-8989',service:'Gel Manicure',staffReq:'Jenny',date:'Hôm nay',time:'11:00 AM',status:'pending',reason:'',source:'Voice',created:'9:41 AM',note:'Khách hỏi giá trước khi chốt',history:['9:41 AM — Booking tạo qua AI Voice (cuộc gọi 42 giây)']},
      {id:'B-102',customer:'Amy Nguyen',phone:'832-***-5555',service:'Deluxe Pedicure',staffReq:'Jenny',date:'Hôm nay',time:'2:30 PM',status:'confirmed',reason:'',source:'SMS',created:'8:15 AM',note:'',history:['8:15 AM — Booking tạo qua SMS','8:20 AM — Confirmed by Front Desk']},
      {id:'B-103',customer:'Saugage Suf',phone:'+1 (832) 555-1212',service:'Full Set',staffReq:'Tina',date:'Hôm nay',time:'11:30 AM',status:'cancelled',reason:'"I\'m busy"',source:'Landing Page',created:'9:02 AM',note:'',history:['9:02 AM — Booking tạo qua Landing Page','9:42 AM — Cancelled: "I\'m busy"']},
      {id:'B-104',customer:'Mary Le',phone:'281-***-8930',service:'Dip Powder',staffReq:'Kevin',date:'Ngày mai',time:'10:00 AM',status:'confirmed',reason:'',source:'Request',created:'Hôm qua',note:'Khách quen, thích ghế số 3',history:['Hôm qua — Booking tạo tại quầy (Request)','Hôm qua — Confirmed by Front Desk']}
    ],
    pendingCheckins:[
      {id:'KC-201',name:'Mina Park',phone:'+1 (832) 555-0140',services:[{name:'Gel Manicure',price:40},{name:'Polish change',price:8}],bookingMatch:'Không tìm thấy lịch hẹn',warning:'Đã chọn ưu tiên thợ nữ tại kiosk',note:'Lần đầu ghé tiệm, muốn màu gel đơn giản',tags:['Ưu tiên thợ nữ'],created:'10:28 AM'},
      {id:'KC-202',name:'Walk-in',phone:'',services:[{name:'Classic Pedicure',price:35}],bookingMatch:'Hồ sơ khách vãng lai',warning:'',note:'Hồ sơ tối giản, chưa có số điện thoại',tags:['Nước ấm'],created:'10:31 AM'}
    ],
    paymentProofs:[
      {id:'PF-301',orderId:'#103',customer:'Mary Le',method:'Zelle',amount:81.19,status:'pending',received:'10:24 AM',reference:'Customer SMS proof received',tip:0,discount:0,discountLabel:'',rating:0}
    ],
    addonRequests:[
      {id:'AR-401',ticketId:'#102·T1',orderId:'#102',customer:'Lisa Tran',staff:'Tina',service:{name:'Polish change',price:8},status:'pending',note:'Staff upsell request from work ticket',created:'10:26 AM'}
    ],
    pastTickets:[
      {id:'#095·T1',orderId:'#095',customer:'Amy Nguyen',day:'Jul 12',daysAgo:1,time:'4:40 PM',services:[{name:'Gel Manicure',price:40}],staff:'Jenny',total:40,method:'Card'},
      {id:'#093·T1',orderId:'#093',customer:'Hannah Kim',day:'Jul 12',daysAgo:1,time:'11:15 AM',services:[{name:'Deluxe Pedicure',price:55}],staff:'Tina',total:55,method:'Cash'},
      {id:'#090·T1',orderId:'#090',customer:'Mary Le',day:'Jul 11',daysAgo:2,time:'3:05 PM',services:[{name:'Dip Powder',price:50},{name:'Polish change',price:8}],staff:'Kevin',total:58,method:'VLinkPay'},
      {id:'#087·T1',orderId:'#087',customer:'Lisa Tran',day:'Jul 10',daysAgo:3,time:'1:30 PM',services:[{name:'Full Set',price:70}],staff:'Tina',total:70,method:'Zelle'},
      {id:'#084·T1',orderId:'#084',customer:'Nancy Vo',day:'Jul 08',daysAgo:5,time:'10:00 AM',services:[{name:'Classic Pedicure',price:35}],staff:'Jenny',total:35,method:'Cash'},
      {id:'#081·T1',orderId:'#081',customer:'Kim Pham',day:'Jul 06',daysAgo:7,time:'2:20 PM',services:[{name:'Fill',price:45}],staff:'Kevin',total:45,method:'Card'},
      {id:'#076·T1',orderId:'#076',customer:'Andy Levi',day:'Jul 04',daysAgo:9,time:'12:10 PM',services:[{name:'Gel Manicure',price:40}],staff:'Jenny',total:40,method:'Cash App'}
    ],
    baseTips:48,
    baseTipCount:4,
    reportBaseline:{grossSales:2692.79,discounts:60,netSales:2632.79,tax:217.21,tips:432,paidOrders:32,tipOrders:28},
    payTotals:{Cash:1250,Card:720,VLinkPay:600,Zelle:400,Venmo:210,'Cash App':150},
    payAccounts:{
      VLinkPay:{acct:'VL-BNB-001',owner:'Bitcoin Nail Bar LLC',note:'QR thanh toán qua VLinkPay',ph:'VLinkPay Business ID / ví nhận',asset:'USDV'},
      Zelle:{acct:'(832) 555-0100',owner:'Bitcoin Nail Bar LLC',note:'Zelle theo số điện thoại tiệm',ph:'Số điện thoại / email nhận Zelle'},
      Venmo:{acct:'@BitcoinNailBar',owner:'Bitcoin Nail Bar',note:'',ph:'Username Venmo (@handle)'},
      'Apple Cash':{acct:'(832) 555-0100',owner:'Bitcoin Nail Bar',note:'',ph:'Số điện thoại Apple Cash'},
      'Cash App':{acct:'$BitcoinNailBar',owner:'Bitcoin Nail Bar',note:'',ph:'$Cashtag'}
    },
    salonCfg:{name:'Bitcoin Nail Bar',phone:'(832) 555-0100',notify:'(832) 555-0777',addr:'2210 Richmond Ave, Houston, TX 77098',review:'g.page/bitcoinnailbar',sched:mkSched([],'09:00','19:00')},
    statusMap:{open:['Open','st-open'],waiting:['Waiting','st-waiting'],inservice:['In Service','st-inservice'],done:['Done','st-done'],ready:['Ready to Pay','st-ready'],closed:['Paid / Closed','st-closed'],void:['Void','st-void']},
    statusI18nKeys:{open:'status.open',waiting:'status.waiting',inservice:'status.inservice',done:'status.done',ready:'status.ready',closed:'status.closed',void:'status.void',pending:'status.pending',confirmed:'status.confirmed',checkedin:'status.checkedin',converted:'status.converted',cancelled:'status.cancelled'},
    roleMeta:{
      Owner:{abbr:'OW',label:'Chủ tiệm',sub:'Toàn quyền',email:'owner'},
      Manager:{abbr:'MG',label:'Quản lý',sub:'Ca sáng',email:'manager'},
      Cashier:{abbr:'CA',label:'Thu ngân',sub:'Ca sáng',email:'cashier'}
    },
    notificationGroups:[
      {key:'urgent',labelKey:'notification.urgent',icon:'triangle-alert',hintKey:'notification.urgentHint'},
      {key:'payment',labelKey:'notification.payment',icon:'wallet-cards',hintKey:'notification.paymentHint'},
      {key:'waiting',labelKey:'notification.waiting',icon:'users-round',hintKey:'notification.waitingHint'},
      {key:'booking',labelKey:'notification.booking',icon:'calendar-days',hintKey:'notification.bookingHint'}
    ],
    bookingStatusMap:{pending:['Pending','st-pending'],confirmed:['Confirmed','st-confirmed'],checkedin:['Checked-in','st-checkedin'],converted:['Converted','st-converted'],cancelled:['Cancelled','st-cancelled']},
    bookingDateFilterLabels:{next7:'date.next7',today:'date.today',tomorrow:'date.tomorrow',custom:'date.custom',all:'date.allBookings'},
    categoryIcons:{Pedicure:'footprints',Manicure:'sparkles',Acrylic:'gem',Dipping:'layers-3'},
    categoryIconChoices:['folder-tree','sparkles','footprints','gem','layers-3','hand','flower-2','eye','brush','droplets']
  };

  const allPermissions=source.permissionCatalog.map(permission=>permission.key);
  source.salonRoles=[
    {name:'Owner',desc:'Chủ tiệm — toàn quyền, không thể sửa hoặc xóa',builtin:true,perms:[...allPermissions]},
    {name:'Manager',desc:'Quản lý vận hành và một phần lương',builtin:false,perms:['booking','customer','orderticket','checkout','void','staff','report']},
    {name:'Cashier',desc:'Lễ tân / thu ngân tại quầy',builtin:false,perms:['booking','customer','orderticket','checkout']},
    {name:'Technician',desc:'Thợ — dùng Staff App, thao tác ticket được giao',builtin:false,perms:['orderticket']}
  ];

  function addOrder(id,customer,time,extra={}){
    const order=Object.assign({id,customer,time,products:[],unassigned:[],tk:0,tip:0,rating:0,method:null,closed:false,voided:false,note:'',tipAlloc:null,timeline:[`${time} — Order created by Front Desk`]},extra);
    source.orders.push(order);
    return order;
  }

  function addTicket(order,ticketServices,staff,status,extra={}){
    const ticket=Object.assign({id:`${order.id}·T${++order.tk}`,orderId:order.id,customer:order.customer,time:order.time,services:ticketServices,staff,status,note:order.note,tip:0,tipShare:0,rating:0,method:null,timeline:[`${order.time} — Ticket tách từ order ${order.id}${staff?` → ${staff}`:''}`]},extra);
    source.tickets.push(ticket);
    return ticket;
  }

  const order101=addOrder('#101','Amy Nguyen','10:05 AM',{note:'Khách thích nước ấm'});
  addTicket(order101,[{name:'Deluxe Pedicure',price:55}],'Jenny','waiting');
  order101.unassigned.push({name:'Gel Manicure',price:40});
  const order104=addOrder('#104','Walk-in','10:20 AM');
  addTicket(order104,[{name:'Dip Powder',price:50}],'Tina','waiting');
  const order102=addOrder('#102','Lisa Tran','10:15 AM');
  addTicket(order102,[{name:'Gel Manicure',price:40}],'Tina','inservice');
  const order103=addOrder('#103','Mary Le','9:45 AM',{products:[{name:'Cuticle Oil',price:12,type:'product'}]});
  addTicket(order103,[{name:'Pedicure',price:55}],'Kevin','done');
  addTicket(order103,[{name:'Polish change',price:8}],'Tina','done');
  const order098=addOrder('#098','Nancy Vo','9:00 AM',{closed:true,tip:12,method:'Zelle'});
  addTicket(order098,[{name:'Full Set',price:70}],'Jenny','closed',{tipShare:12});
  const order099=addOrder('#099','Kim Pham','9:30 AM',{voided:true,voidReason:'Tạo nhầm'});
  addTicket(order099,[{name:'Classic Manicure',price:25}],null,'void');
  const order105=addOrder('#105','Olivia Pham','10:35 AM');
  addTicket(order105,[{name:'Classic Pedicure',price:35}],'Kevin','waiting');
  const order106=addOrder('#106','Sophia Bui','10:50 AM',{note:'Thích form almond'});
  addTicket(order106,[{name:'Full Set',price:70}],'Tina','inservice');
  const order107=addOrder('#107','Linda Ho','11:05 AM');
  addTicket(order107,[{name:'Classic Pedicure',price:35}],'Kevin','inservice');
  const order108=addOrder('#108','Chloe Dao','11:20 AM',{note:'Ưu tiên màu trung tính'});
  addTicket(order108,[{name:'Gel Manicure',price:40}],'Jenny','done');
  const order109=addOrder('#109','Jessica Truong','11:35 AM',{voided:true,voidReason:'Customer changed mind'});
  addTicket(order109,[{name:'Classic Manicure',price:25}],null,'void',{voidReason:'Customer changed mind'});
  const order110=addOrder('#110','Emily Nguyen','11:50 AM',{note:'Dị ứng latex'});
  order110.unassigned.push({name:'Dip Powder',price:50});

  const clone=value=>JSON.parse(JSON.stringify(value));
  root.NexoraPosData=Object.freeze({createState:()=>clone(source)});
})(window);
